import { createClient } from '@supabase/supabase-js';
import OpenAI from 'openai';
import { Octokit } from '@octokit/rest';
import { DateTime } from 'luxon';
import { zonedTimeToUtc, utcToZonedTime } from 'date-fns-tz';
import { format } from 'date-fns';

const supabaseUrl = process.env.SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_KEY;

if (!supabaseUrl || !supabaseKey) {
  console.error('Supabase credentials are required');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

async function getRepositoryContent(octokit: Octokit, owner: string, repo: string, path: string) {
  try {
    const response = await octokit.repos.getContent({
      owner,
      repo,
      path,
    });

    if (Array.isArray(response.data)) {
      return null;
    }

    if ('content' in response.data) {
      return Buffer.from(response.data.content, 'base64').toString('utf-8');
    }

    return null;
  } catch (error) {
    console.error(`Error fetching content for ${path}:`, error);
    return null;
  }
}

async function analyzeSeoContent(content: string) {
  try {
    const response = await openai.chat.completions.create({
      model: 'gpt-4-turbo-preview',
      messages: [
        {
          role: 'system',
          content: 'You are an SEO expert. Analyze the HTML content and suggest improvements for SEO.',
        },
        {
          role: 'user',
          content: `Analyze this HTML content and suggest SEO improvements:\n\n${content}`,
        },
      ],
    });

    return response.choices[0].message.content;
  } catch (error) {
    console.error('Error analyzing content with AI:', error);
    return null;
  }
}

async function createPullRequest(
  octokit: Octokit,
  owner: string,
  repo: string,
  changes: Array<{ path: string; content: string }>,
  baseBranch: string
) {
  try {
    // Create a new branch
    const timestamp = DateTime.now().toFormat('yyyyMMddHHmmss');
    const branchName = `seo-improvements-${timestamp}`;

    // Get the SHA of the latest commit on the base branch
    const { data: ref } = await octokit.git.getRef({
      owner,
      repo,
      ref: `heads/${baseBranch}`,
    });

    // Create the new branch
    await octokit.git.createRef({
      owner,
      repo,
      ref: `refs/heads/${branchName}`,
      sha: ref.object.sha,
    });

    // Create commits for each file
    for (const change of changes) {
      const { data: currentFile } = await octokit.repos.getContent({
        owner,
        repo,
        path: change.path,
        ref: branchName,
      });

      if (Array.isArray(currentFile)) continue;

      await octokit.repos.createOrUpdateFileContents({
        owner,
        repo,
        path: change.path,
        message: `SEO improvements for ${change.path}`,
        content: Buffer.from(change.content).toString('base64'),
        branch: branchName,
        sha: currentFile.sha,
      });
    }

    // Create pull request
    const { data: pr } = await octokit.pulls.create({
      owner,
      repo,
      title: 'SEO Improvements',
      head: branchName,
      base: baseBranch,
      body: 'Automated SEO improvements generated by AI analysis.',
    });

    return pr.number;
  } catch (error) {
    console.error('Error creating pull request:', error);
    return null;
  }
}

async function shouldRunAutomation(userId: string): Promise<boolean> {
  try {
    const { data: preferences, error } = await supabase
      .from('user_preferences')
      .select('timezone, automation_schedule, automation_enabled')
      .eq('user_id', userId)
      .single();

    if (error) throw error;
    if (!preferences || !preferences.automation_enabled) return false;

    const now = new Date();
    const userTime = utcToZonedTime(now, preferences.timezone);
    const scheduleTime = new Date(`2000-01-01T${preferences.automation_schedule}`);
    
    // Convert current time to HH:mm format for comparison
    const currentTimeStr = format(userTime, 'HH:mm');
    const scheduleTimeStr = format(scheduleTime, 'HH:mm');

    // Run if current time matches schedule time (within the 15-minute window)
    const currentMinutes = parseInt(currentTimeStr.split(':')[0]) * 60 + parseInt(currentTimeStr.split(':')[1]);
    const scheduleMinutes = parseInt(scheduleTimeStr.split(':')[0]) * 60 + parseInt(scheduleTimeStr.split(':')[1]);
    const diff = Math.abs(currentMinutes - scheduleMinutes);

    return diff <= 15; // Run if within 15 minutes of scheduled time
  } catch (error) {
    console.error('Error checking automation schedule:', error);
    return false;
  }
}

async function createAutomationLog(userId: string, repositoryId: string): Promise<string> {
  try {
    const { data, error } = await supabase
      .from('seo_automation_logs')
      .insert({
        user_id: userId,
        repository_id: repositoryId,
        status: 'in_progress',
        started_at: new Date().toISOString(),
      })
      .select()
      .single();

    if (error) throw error;
    return data.id;
  } catch (error) {
    console.error('Error creating automation log:', error);
    throw error;
  }
}

async function runAutomation() {
  try {
    // Get all users with repositories
    const { data: users, error } = await supabase
      .from('users')
      .select(`
        id,
        repositories!inner(
          id,
          owner,
          name,
          default_branch
        )
      `);

    if (error) throw error;

    for (const user of users) {
      const shouldRun = await shouldRunAutomation(user.id);
      if (!shouldRun) continue;

      for (const repo of user.repositories) {
        const changes = [];
        let logId: string | null = null;

        try {
          logId = await createAutomationLog(user.id, repo.id);
          
          // Get GitHub token from user settings
          const { data: settings, error: settingsError } = await supabase
            .from('user_settings')
            .select('github_token')
            .eq('user_id', user.id)
            .single();
            
          if (settingsError || !settings?.github_token) {
            console.error('GitHub token not found for user:', user.id);
            continue;
          }

          // Initialize GitHub client
          const octokit = new Octokit({
            auth: settings.github_token,
          });

          // Get HTML files
          const { data: files } = await octokit.repos.getContent({
            owner: repo.owner,
            repo: repo.name,
            path: '',
          });

          const htmlFiles = Array.isArray(files)
            ? files.filter((f) => f.name.endsWith('.html'))
            : [];

          for (const file of htmlFiles) {
            const content = await getRepositoryContent(
              octokit,
              repo.owner,
              repo.name,
              file.path
            );

            if (!content) continue;

            const analysis = await analyzeSeoContent(content);
            if (!analysis) continue;

            // Store the suggested changes
            const { data: seoChange, error: changeError } = await supabase
              .from('seo_changes')
              .insert([
                {
                  automation_log_id: logId,
                  file_path: file.path,
                  element_type: 'content',
                  old_value: content,
                  new_value: analysis,
                  confidence_score: 0.8,
                  status: 'pending',
                },
              ])
              .select()
              .single();

            if (changeError) {
              console.error('Error storing SEO change:', changeError);
              continue;
            }

            changes.push({
              path: file.path,
              content: analysis,
            });
          }

          if (changes.length > 0) {
            // Create pull request
            const prNumber = await createPullRequest(
              octokit,
              repo.owner,
              repo.name,
              changes,
              repo.default_branch || 'main'
            );

            if (prNumber) {
              // Update automation log with success
              await supabase
                .from('seo_automation_logs')
                .update({
                  status: 'completed',
                  completed_at: new Date().toISOString(),
                  changes_count: changes.length,
                  pull_request_number: prNumber,
                })
                .eq('id', logId);

              // Send notification if enabled
              await supabase
                .from('user_notifications')
                .insert([
                  {
                    user_id: user.id,
                    type: 'seo_changes',
                    title: `SEO changes for ${repo.name}`,
                    message: `Created pull request #${prNumber} with ${changes.length} SEO improvements`,
                    status: 'unread',
                  },
                ]);
            }
          } else {
            // Update automation log with no changes
            await supabase
              .from('seo_automation_logs')
              .update({
                status: 'completed',
                completed_at: new Date().toISOString(),
                changes_count: 0,
              })
              .eq('id', logId);
          }
        } catch (error: any) {
          console.error(`Error processing repository ${repo.name}:`, error);
          
          // Update automation log with error
          if (logId) {
            await supabase
              .from('seo_automation_logs')
              .update({
                status: 'failed',
                completed_at: new Date().toISOString(),
                error_message: error.message || 'Unknown error occurred',
              })
              .eq('id', logId);
          }
        }
      }
    }
  } catch (error) {
    console.error('Error running automation:', error);
  }
}

runAutomation(); 